version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      DB_HOST: "db" 
      DB_PORT: "5432"  
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      
      
    ports:
      - "8020:8020"  
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:


